In [3]:
import requests
import pandas as pd

In [4]:
base_url = 'https://python.zach.lol/api/v1/sales'
response = requests.get(base_url)

sale_data = response.json()
sale= pd.DataFrame(sale_data['payload']['sales'])

In [5]:
sale

      item  sale_amount                      sale_date  sale_id  store
0        1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1        1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2        1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3        1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4        1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1
5        1         12.0  Sun, 06 Jan 2013 00:00:00 GMT        6      1
6        1         10.0  Mon, 07 Jan 2013 00:00:00 GMT        7      1
7        1          9.0  Tue, 08 Jan 2013 00:00:00 GMT        8      1
8        1         12.0  Wed, 09 Jan 2013 00:00:00 GMT        9      1
9        1          9.0  Thu, 10 Jan 2013 00:00:00 GMT       10      1
10       1          9.0  Fri, 11 Jan 2013 00:00:00 GMT       11      1
11       1          7.0  Sat, 12 Jan 2013 00:00:00 GMT       12      1
12       1         10.0  Sun, 13 Jan 2013 00:00:00 GMT       13      1
13       1         12.0  Mon, 14 Jan 2013 00:00:00 GMT       14      1
14       1          5.0  Tue, 15 Jan 2013 00:00:00 GMT       15      1
15       1          7.0  Wed, 16 Jan 2013 00:00:00 GMT       16      1
16       1         16.0  Thu, 17 Jan 2013 00:00:00 GMT       17      1
17       1          7.0  Fri, 18 Jan 2013 00:00:00 GMT       18      1
18       1         18.0  Sat, 19 Jan 2013 00:00:00 GMT       19      1
19       1         15.0  Sun, 20 Jan 2013 00:00:00 GMT       20      1
20       1          8.0  Mon, 21 Jan 2013 00:00:00 GMT       21      1
21       1          7.0  Tue, 22 Jan 2013 00:00:00 GMT       22      1
22       1          9.0  Wed, 23 Jan 2013 00:00:00 GMT       23      1
23       1          8.0  Thu, 24 Jan 2013 00:00:00 GMT       24      1
24       1         14.0  Fri, 25 Jan 2013 00:00:00 GMT       25      1
25       1         12.0  Sat, 26 Jan 2013 00:00:00 GMT       26      1
26       1         12.0  Sun, 27 Jan 2013 00:00:00 GMT       27      1
27       1         11.0  Mon, 28 Jan 2013 00:00:00 GMT       28      1
28       1          6.0  Tue, 29 Jan 2013 00:00:00 GMT       29      1
29       1          9.0  Wed, 30 Jan 2013 00:00:00 GMT       30      1
...    ...          ...                            ...      ...    ...
4970     1         18.0  Thu, 11 Aug 2016 00:00:00 GMT     4971      3
4971     1         42.0  Fri, 12 Aug 2016 00:00:00 GMT     4972      3
4972     1         23.0  Sat, 13 Aug 2016 00:00:00 GMT     4973      3
4973     1         44.0  Sun, 14 Aug 2016 00:00:00 GMT     4974      3
4974     1         22.0  Mon, 15 Aug 2016 00:00:00 GMT     4975      3
4975     1         21.0  Tue, 16 Aug 2016 00:00:00 GMT     4976      3
4976     1         33.0  Wed, 17 Aug 2016 00:00:00 GMT     4977      3
4977     1         37.0  Thu, 18 Aug 2016 00:00:00 GMT     4978      3
4978     1         26.0  Fri, 19 Aug 2016 00:00:00 GMT     4979      3
4979     1         36.0  Sat, 20 Aug 2016 00:00:00 GMT     4980      3
4980     1         42.0  Sun, 21 Aug 2016 00:00:00 GMT     4981      3
4981     1         19.0  Mon, 22 Aug 2016 00:00:00 GMT     4982      3
4982     1         32.0  Tue, 23 Aug 2016 00:00:00 GMT     4983      3
4983     1         35.0  Wed, 24 Aug 2016 00:00:00 GMT     4984      3
4984     1         26.0  Thu, 25 Aug 2016 00:00:00 GMT     4985      3
4985     1         33.0  Fri, 26 Aug 2016 00:00:00 GMT     4986      3
4986     1         39.0  Sat, 27 Aug 2016 00:00:00 GMT     4987      3
4987     1         39.0  Sun, 28 Aug 2016 00:00:00 GMT     4988      3
4988     1         23.0  Mon, 29 Aug 2016 00:00:00 GMT     4989      3
4989     1         36.0  Tue, 30 Aug 2016 00:00:00 GMT     4990      3
4990     1         31.0  Wed, 31 Aug 2016 00:00:00 GMT     4991      3
4991     1         28.0  Thu, 01 Sep 2016 00:00:00 GMT     4992      3
4992     1         27.0  Fri, 02 Sep 2016 00:00:00 GMT     4993      3
4993     1         37.0  Sat, 03 Sep 2016 00:00:00 GMT     4994      3
4994     1         38.0  Sun, 04 Sep 2016 00:00:00 GMT     4995      3
4995     1         23.0  Mon, 05 Sep 2016 00:00:00 GMT     4996      3
4996     1         22.0  Tue, 06 Sep 2016 00:00:00 GMT     4997      3
4997     1         21.0  Wed, 07 Sep 2016 00:00:00 GMT     4998      3
4998     1         22.0  Thu, 08 Sep 2016 00:00:00 GMT     4999      3
4999     1         24.0  Fri, 09 Sep 2016 00:00:00 GMT     5000      3

[5000 rows x 5 columns]

In [8]:
def acquire():
    
    #response = requests.get(base_url)
    for page in range(1,5):
        base_url = 'https://python.zach.lol/api/v1/sales'
        response = requests.get(base_url + '?page={}'.format(page))
        sale= pd.DataFrame(response.json()['payload']['sales'])
        sales = pd.concat([sales, sale])
    return sales

In [20]:
def acquire():
    for page in range(1,5):
        base_url = 'https://python.zach.lol/api/v1/sales'
        response = requests.get(base_url + '?page={}'.format(page))
        sales = pd.DataFrame()
        sale= pd.DataFrame(response.json()['payload']['sales'])
        sales = pd.concat([sales, sale])
    return sales

In [21]:
acquire()

      item  sale_amount                      sale_date  sale_id  store
0        1         13.0  Tue, 28 Jan 2014 00:00:00 GMT    15001      9
1        1         16.0  Wed, 29 Jan 2014 00:00:00 GMT    15002      9
2        1         15.0  Thu, 30 Jan 2014 00:00:00 GMT    15003      9
3        1         20.0  Fri, 31 Jan 2014 00:00:00 GMT    15004      9
4        1         18.0  Sat, 01 Feb 2014 00:00:00 GMT    15005      9
5        1         17.0  Sun, 02 Feb 2014 00:00:00 GMT    15006      9
6        1          7.0  Mon, 03 Feb 2014 00:00:00 GMT    15007      9
7        1         14.0  Tue, 04 Feb 2014 00:00:00 GMT    15008      9
8        1         16.0  Wed, 05 Feb 2014 00:00:00 GMT    15009      9
9        1         15.0  Thu, 06 Feb 2014 00:00:00 GMT    15010      9
10       1         18.0  Fri, 07 Feb 2014 00:00:00 GMT    15011      9
11       1         21.0  Sat, 08 Feb 2014 00:00:00 GMT    15012      9
12       1         15.0  Sun, 09 Feb 2014 00:00:00 GMT    15013      9
13       1         12.0  Mon, 10 Feb 2014 00:00:00 GMT    15014      9
14       1         12.0  Tue, 11 Feb 2014 00:00:00 GMT    15015      9
15       1         19.0  Wed, 12 Feb 2014 00:00:00 GMT    15016      9
16       1         14.0  Thu, 13 Feb 2014 00:00:00 GMT    15017      9
17       1         20.0  Fri, 14 Feb 2014 00:00:00 GMT    15018      9
18       1         15.0  Sat, 15 Feb 2014 00:00:00 GMT    15019      9
19       1         21.0  Sun, 16 Feb 2014 00:00:00 GMT    15020      9
20       1          9.0  Mon, 17 Feb 2014 00:00:00 GMT    15021      9
21       1         17.0  Tue, 18 Feb 2014 00:00:00 GMT    15022      9
22       1         19.0  Wed, 19 Feb 2014 00:00:00 GMT    15023      9
23       1         13.0  Thu, 20 Feb 2014 00:00:00 GMT    15024      9
24       1         22.0  Fri, 21 Feb 2014 00:00:00 GMT    15025      9
25       1         15.0  Sat, 22 Feb 2014 00:00:00 GMT    15026      9
26       1         25.0  Sun, 23 Feb 2014 00:00:00 GMT    15027      9
27       1         13.0  Mon, 24 Feb 2014 00:00:00 GMT    15028      9
28       1         17.0  Tue, 25 Feb 2014 00:00:00 GMT    15029      9
29       1         16.0  Wed, 26 Feb 2014 00:00:00 GMT    15030      9
...    ...          ...                            ...      ...    ...
4970     2         59.0  Thu, 07 Sep 2017 00:00:00 GMT    19971      1
4971     2         65.0  Fri, 08 Sep 2017 00:00:00 GMT    19972      1
4972     2         71.0  Sat, 09 Sep 2017 00:00:00 GMT    19973      1
4973     2         64.0  Sun, 10 Sep 2017 00:00:00 GMT    19974      1
4974     2         44.0  Mon, 11 Sep 2017 00:00:00 GMT    19975      1
4975     2         58.0  Tue, 12 Sep 2017 00:00:00 GMT    19976      1
4976     2         57.0  Wed, 13 Sep 2017 00:00:00 GMT    19977      1
4977     2         71.0  Thu, 14 Sep 2017 00:00:00 GMT    19978      1
4978     2         60.0  Fri, 15 Sep 2017 00:00:00 GMT    19979      1
4979     2         75.0  Sat, 16 Sep 2017 00:00:00 GMT    19980      1
4980     2         58.0  Sun, 17 Sep 2017 00:00:00 GMT    19981      1
4981     2         47.0  Mon, 18 Sep 2017 00:00:00 GMT    19982      1
4982     2         66.0  Tue, 19 Sep 2017 00:00:00 GMT    19983      1
4983     2         61.0  Wed, 20 Sep 2017 00:00:00 GMT    19984      1
4984     2         66.0  Thu, 21 Sep 2017 00:00:00 GMT    19985      1
4985     2         70.0  Fri, 22 Sep 2017 00:00:00 GMT    19986      1
4986     2         85.0  Sat, 23 Sep 2017 00:00:00 GMT    19987      1
4987     2         73.0  Sun, 24 Sep 2017 00:00:00 GMT    19988      1
4988     2         49.0  Mon, 25 Sep 2017 00:00:00 GMT    19989      1
4989     2         61.0  Tue, 26 Sep 2017 00:00:00 GMT    19990      1
4990     2         57.0  Wed, 27 Sep 2017 00:00:00 GMT    19991      1
4991     2         55.0  Thu, 28 Sep 2017 00:00:00 GMT    19992      1
4992     2         66.0  Fri, 29 Sep 2017 00:00:00 GMT    19993      1
4993     2         79.0  Sat, 30 Sep 2017 00:00:00 GMT    19994      1
4994     2         60.0  Sun, 01 Oct 2017 00:00:00 GMT    19995      1
4995     2         56.0  Mon, 02 Oct 2017 00:00:00 GMT    19996      1
4996     2         55.0  Tue, 03 Oct 2017 00:00:00 GMT    19997      1
4997     2         55.0  Wed, 04 Oct 2017 00:00:00 GMT    19998      1
4998     2         59.0  Thu, 05 Oct 2017 00:00:00 GMT    19999      1
4999     2         54.0  Fri, 06 Oct 2017 00:00:00 GMT    20000      1

[5000 rows x 5 columns]

In [12]:
def get_sales():
    base_url = "http://python.zach.lol"
    response = requests.get(base_url + "/api/v1/sales")

   #maxpage = response.json()["payload"]["max_page"] + 1
    sales = pd.DataFrame()

    for page in range(1,5):
        response = requests.get(base_url + "/api/v1/sales?page={}".format(page))
        sale_page = pd.DataFrame(response.json()["payload"]["sales"])
        sales = pd.concat([sales,sale_page])
    return sales

      item  sale_amount                      sale_date  sale_id  store
0        1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1        1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2        1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3        1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4        1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1
5        1         12.0  Sun, 06 Jan 2013 00:00:00 GMT        6      1
6        1         10.0  Mon, 07 Jan 2013 00:00:00 GMT        7      1
7        1          9.0  Tue, 08 Jan 2013 00:00:00 GMT        8      1
8        1         12.0  Wed, 09 Jan 2013 00:00:00 GMT        9      1
9        1          9.0  Thu, 10 Jan 2013 00:00:00 GMT       10      1
10       1          9.0  Fri, 11 Jan 2013 00:00:00 GMT       11      1
11       1          7.0  Sat, 12 Jan 2013 00:00:00 GMT       12      1
12       1         10.0  Sun, 13 Jan 2013 00:00:00 GMT       13      1
13       1         12.0  Mon, 14 Jan 2013 00:00:00 GMT       14      1
14       1          5.0  Tue, 15 Jan 2013 00:00:00 GMT       15      1
15       1          7.0  Wed, 16 Jan 2013 00:00:00 GMT       16      1
16       1         16.0  Thu, 17 Jan 2013 00:00:00 GMT       17      1
17       1          7.0  Fri, 18 Jan 2013 00:00:00 GMT       18      1
18       1         18.0  Sat, 19 Jan 2013 00:00:00 GMT       19      1
19       1         15.0  Sun, 20 Jan 2013 00:00:00 GMT       20      1
20       1          8.0  Mon, 21 Jan 2013 00:00:00 GMT       21      1
21       1          7.0  Tue, 22 Jan 2013 00:00:00 GMT       22      1
22       1          9.0  Wed, 23 Jan 2013 00:00:00 GMT       23      1
23       1          8.0  Thu, 24 Jan 2013 00:00:00 GMT       24      1
24       1         14.0  Fri, 25 Jan 2013 00:00:00 GMT       25      1
25       1         12.0  Sat, 26 Jan 2013 00:00:00 GMT       26      1
26       1         12.0  Sun, 27 Jan 2013 00:00:00 GMT       27      1
27       1         11.0  Mon, 28 Jan 2013 00:00:00 GMT       28      1
28       1          6.0  Tue, 29 Jan 2013 00:00:00 GMT       29      1
29       1          9.0  Wed, 30 Jan 2013 00:00:00 GMT       30      1
...    ...          ...                            ...      ...    ...
4970     2         59.0  Thu, 07 Sep 2017 00:00:00 GMT    19971      1
4971     2         65.0  Fri, 08 Sep 2017 00:00:00 GMT    19972      1
4972     2         71.0  Sat, 09 Sep 2017 00:00:00 GMT    19973      1
4973     2         64.0  Sun, 10 Sep 2017 00:00:00 GMT    19974      1
4974     2         44.0  Mon, 11 Sep 2017 00:00:00 GMT    19975      1
4975     2         58.0  Tue, 12 Sep 2017 00:00:00 GMT    19976      1
4976     2         57.0  Wed, 13 Sep 2017 00:00:00 GMT    19977      1
4977     2         71.0  Thu, 14 Sep 2017 00:00:00 GMT    19978      1
4978     2         60.0  Fri, 15 Sep 2017 00:00:00 GMT    19979      1
4979     2         75.0  Sat, 16 Sep 2017 00:00:00 GMT    19980      1
4980     2         58.0  Sun, 17 Sep 2017 00:00:00 GMT    19981      1
4981     2         47.0  Mon, 18 Sep 2017 00:00:00 GMT    19982      1
4982     2         66.0  Tue, 19 Sep 2017 00:00:00 GMT    19983      1
4983     2         61.0  Wed, 20 Sep 2017 00:00:00 GMT    19984      1
4984     2         66.0  Thu, 21 Sep 2017 00:00:00 GMT    19985      1
4985     2         70.0  Fri, 22 Sep 2017 00:00:00 GMT    19986      1
4986     2         85.0  Sat, 23 Sep 2017 00:00:00 GMT    19987      1
4987     2         73.0  Sun, 24 Sep 2017 00:00:00 GMT    19988      1
4988     2         49.0  Mon, 25 Sep 2017 00:00:00 GMT    19989      1
4989     2         61.0  Tue, 26 Sep 2017 00:00:00 GMT    19990      1
4990     2         57.0  Wed, 27 Sep 2017 00:00:00 GMT    19991      1
4991     2         55.0  Thu, 28 Sep 2017 00:00:00 GMT    19992      1
4992     2         66.0  Fri, 29 Sep 2017 00:00:00 GMT    19993      1
4993     2         79.0  Sat, 30 Sep 2017 00:00:00 GMT    19994      1
4994     2         60.0  Sun, 01 Oct 2017 00:00:00 GMT    19995      1
4995     2         56.0  Mon, 02 Oct 2017 00:00:00 GMT    19996      1
4996     2         55.0  Tue, 03 Oct 2017 00:00:00 GMT    19997      1
4997     2         55.0  Wed, 04 Oct 2017 00:00:00 GMT    19998      1
4998     2         59.0  Thu, 05 Oct 2017 00:00:00 GMT    19999      1
4999     2         54.0  Fri, 06 Oct 2017 00:00:00 GMT    20000      1

[20000 rows x 5 columns]